name: Build and Deploy Spring Microservices Application for CTSE Assignment

on: 
  push:
    branches:
      - main
      - test/ci-cd
  pull_request:
    branches:
      - main

jobs:
  cd-pipeline:
    name: Build and Deploy Spring Microservices Application
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - api-gateway
          - config-server
          - department-service
          - employee-service
          - service-registry

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Environment Variables
        env:
          MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
          MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
        run: bash ./config-server/setup_env.sh

      - name: Run Unit Tests for ${{ matrix.service }}
        run: mvn -B test --file ${{ matrix.service }}/pom.xml

      - name: Build the Application for ${{ matrix.service }}
        run: mvn -B package --file ${{ matrix.service }}/pom.xml

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image for ${{ matrix.service }}
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ctse-${{ matrix.service }}:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ctse-${{ matrix.service }}:latest
