name: Test and Build Spring Microservices Application for CTSE Assignment

on: 
  pull_request:
    branches:
      - main

jobs:
    ci-pipeline:
      name: Test and Build Spring Microservices Application
      runs-on: ubuntu-latest
      strategy:
        matrix:
          service:
            - api-gateway
            - config-server
            - department-service
            - employee-service
            - service-registry

      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup JDK 17
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: 17

        - name: Set up Environment Variables
          env:
            MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
            MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }} 
          run: bash ./config-server/setup_env.sh

        - name: Run Unit Tests for ${{ matrix.service }}
          run: mvn -B test --file ${{ matrix.service }}/pom.xml

        - name: Build the Application for ${{ matrix.service }}
          run: |
            mvn clean
            mvn -B package --file ${{ matrix.service }}/pom.xml
