name: Build and Deploy spring microservices application CTSE assignment

on: 
  push:
    branches:
      - ci-cd

jobs:
  build-deploy:
    name: Build and Deploy spring microservices application
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - api-gateway
          - config-server
          - department-service
          - employee-service
          - service-registry

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Unit tests for ${{ matrix.service }}
        run: mvn -B test --file ${{ matrix.service }}/pom.xml

      - name: Build the application for ${{ matrix.service }}
        run: mvn -B package --file ${{ matrix.service }}/pom.xml

      - name: Build Docker image for ${{ matrix.service }}
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          dockerfile: Dockerfile
          push: false
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/spring-boot-microservice-ctse-assignment:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          dockerfile: Dockerfile
          push: true
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/spring-boot-microservice-ctse-assignment:latest
